apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: greenstreet
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"

spec:
  selector:
    app: backend

  ports:
  - port: 8000
    targetPort: 8000

  type: ClusterIP
