apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: greenstreet

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
            memory: {{ .Values.frontend.resources.requests.memory | quote }}

          limits:
            cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
            memory: {{ .Values.frontend.resources.limits.memory | quote }}
