apiVersion: v1
kind: Secret

metadata:
  name: minio-secret
  namespace: greenstreet

type: opaque

stringData:
  root-user: {{ .Values.minio.credentials.rootUser | quote }}
  root-password: {{ .Values.minio.credentials.rootPassword | quote }}
