apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: greenstreet

type: Opaque

stringData:
  username: {{ .Values.postgres.credentials.username | quote }}
  password: {{ .Values.postgres.credentials.password | quote }}
