apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: greenstreet

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: compose_backend:latest
          imagePullPolicy: Never

          env:
            - name: DATABASE_URL
              value: postgresql://greenstreet:greenstreet@postgres:5432/greenstreet

            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MINIO_BUCKET_NAME

            - name: MINIO_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MINIO_PUBLIC_URL

            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user

            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password

            - name: MINIO_ENDPOINT
              value: minio:9000

            - name: MINIO_SECURE
              value: "false"

          ports:
            - containerPort: 8000
