apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: greenstreet
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:shreedharjolad/gidamaragalu.git
    targetRevision: develop
    path: helm/charts/greenstreet

    helm:
      valueFiles:
        - values-kind.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: greenstreet

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true