services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: greenstreet
      POSTGRES_USER: greenstreet
      POSTGRES_PASSWORD: greenstreet

    ports:
      - "5432:5432"

    volumes:
     - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../../backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://greenstreet:greenstreet@postgres:5432/greenstreet

    depends_on:
      - postgres

  frontend:
    build: ../../frontend

    ports:
      - "4321:80"

    depends_on:
      - backend

  minio:
    image: minio/minio

    container_name: minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
