apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: greenstreet

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres

        image: postgres:17

        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_NAME

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        - name: MINIO_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MINIO_BUCKET_NAME

        - name: MINIO_PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MINIO_PUBLIC_URL

        ports:
        - containerPort: 5432

        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
