apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: greenstreet

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: compose_frontend:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"

          limits:
            cpu: "250m"
            memory: "128Mi"
