backend:
  replicaCount: 2
  image:
    repository: compose_backend
    tag: latest
    pullPolicy: Never

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    cpuUtilization: 50

  pdb:
    enabled: true
    minAvailable: 1

frontend:
  replicaCount: 1
  image:
    repository: compose_frontend
    tag: latest
    pullPolicy: Never

config:
  corsOrigins: http://greenstreet.local:8080

  database:
    name: greenstreet

  minio:
    bucketName: tree-photos
    publicUrl: http://minio:9000

ingress:
  host: greenstreet.local

postgres:

  image:
    repository: postgres
    tag: "17"

  storage: 2Gi

  credentials:
    username: greenstreet
    password: greenstreet

  resources:

    requests:
      cpu: "250m"
      memory: "512Mi"

    limits:
      cpu: "500m"
      memory: "1Gi"

minio:

  image:
    repository: minio/minio
    tag: latest

  storage: 2Gi

  credentials:
    rootUser: admin
    rootPassword: password123

  resources:

    requests:
      cpu: "250m"
      memory: "256Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"