backend:
  image:
    repository: compose_backend
    tag: latest
    pullPolicy: Never

frontend:
  image:
    repository: compose_frontend
    tag: latest
    pullPolicy: Never

ingress:
  host: greenstreet.local

config:
  corsOrigins:
    - http://greenstreet.local:8080