backend:
  image:
    repository: compose_backend
    tag: latest
    pullPolicy: Never

frontend:
  image:
    repository: compose_frontend
    tag: latest
    pullPolicy: Never

ingress:
  host: greenstreet.192.168.1.7.nip.io

config:
  corsOrigins:
    - http://greenstreet.192.168.1.7.nip.io:8080